backend:
  name: git-gateway
  branch: cn
media_folder: "media"
local_backend: true
collections:
  - name: "home"
    label: "Home"
    files:
      - label: "Home"
        name: "home"
        file: "content/index.md"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "home",
            }
          - {label: Tagline, name: tagline, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown} 
          - label: "Topics"
            name: "topics"
            widget: "list"
            fields:
            - { label: Title, name: title, widget: string }
            - { label: Image, name: image, widget: image }
            - { label: Link, name: link, widget: string }
  - name: "theory"
    label: "All Articles"
    folder: "content/theory"
    create: true
    identifier_field: name
    slug: "{{key}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "article",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "hidden",
          default: "theory",
        }
      - {
          label: "Key (Short name of the theory. Can't be changed after the theory is created.)",
          name: "key",
          widget: "string",
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Sort order", name: "sortOrder", widget: "number" }
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "theoryCategories"
        required: true
        displayFields: ["name"]
        valueField: "key"
        searchFields: ["name"]
      - { label: "Introduction", name: "intro", widget: "markdown", required: false }
      - { label: "A new perspective", name: "perspective", widget: "markdown", required: false }
      - { label: "In Practice", name: "inPractice", widget: "markdown", required: false }
      - { label: "Body (not used anymore)", name: "body", widget: "markdown", required: false }
      - label: "FAQ"
        name: "faq"
        widget: "list"
        fields:
          - { label: Question, name: question, widget: string }
          - { label: Answer, name: answer, widget: markdown, minimal: true }
      - label: "Related Theory"
        name: "relatedTheory"
        widget: "relation"
        collection: "theory"
        required: false
        displayFields: ["name"]
        valueField: "key"
        searchFields: ["name"]
        multiple: true
        optionsLength: 1000
  - name: "theoryCategories"
    hide: true
    label: "Theory Categories"
    folder: "content/theoryCategories"
    create: false
    identifier_field: name
    fields:
      - {
          label: "Tags",
          name: "tags",
          widget: "hidden",
          default: "theoryCategories",
        }
      - {
          label: "Key (Short name of the category. Can't be changed after the category is created.)",
          name: "key",
          widget: "string",
        }
      - { label: "Name", name: "name", widget: "string" }
  - name: "cases"
    label: "Case Studies"
    folder: "content/cases"
    create: true
    identifier_field: name
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "case" }
      - {
          label: "Tags",
          name: "tags",
          widget: "hidden",
          default: "cases",
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime"}
      - {
          label: "Introduction",
          name: "introduction",
          widget: "markdown",
          minimal: true,
        }
      - {
          label: "Industry",
          name: "industry",
          widget: "select",
          options: [
            "A. Agriculture, forestry and fishing", 
            "B. Mining and quarrying",
            "C、 制造业 ",
            "D、 电力、燃气、蒸汽和空调供应",
            "E. Water supply; sewerage, waste management and remediation activities",
            "F. Construction",
            "G、 批发和零售业；汽车和摩托车修理 美国 >500 营利组织",
            "H. Transportation and storage",
            "1、 食宿服务活动",
            "J、 信息与通信",
            "K. Financial and insurance activities",
            "L. Real estate activities",
            "M. Professional, scientific and technical activities",
            "N. Administrative and support service activities",
            "O. Public administration and defence; compulsory social security",
            "P.教育",
            "Q、 人类健康和社会工作活动 ",
            "R、 艺术、娱乐 ",
            "公共服务-美国-4000名员工-非盈利",
            "T. Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use",
            "U. Activities of extraterritorial organizations and bodies",
            "五、 其他 "
            ],
        }
      - {
          label: "Geography",
          name: "geography",
          widget: "select",
          options: ["巴西", "加拿大", "China", "Egypt", "法国", "德国", "全球", "India", "日本", "Morrocco", "荷兰", "新西兰", "Philippines", "Switzerland", "美国"],
        }
      - {
          label: "Company size",
          name: "companySize",
          widget: "select",
          options: ["1-100", "101-200", "201-500", "> 500"],
        }
      - {
          label: "Profit",
          name: "profit",
          widget: "select",
          options: ["营利组织", "非营利"],
        }
      - label: "Theory"
        name: "theory"
        widget: "list"
        fields:
          - {
              label: Topic,
              name: topic,
              widget: relation,
              collection: "theory",
              displayFields: ["name"],
              valueField: "key",
              searchFields: ["name"],
            }
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown, minimal: true }
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    identifier_field: name
    slug: "{{name}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "content",
        }
      - {label: Title, name: name, widget: string}
      - {label: Body, name: body, widget: markdown} 
  - label: "Configuration"
    name: "configuration"
    files:
      - label: "Footer"
        name: "footer"
        file: "_data/footer.json"
        fields:
          - label: "Footer Links"
            name: "footerLinks"
            widget: "list"
            fields:
            - { label: Title, name: title, widget: string }
            - { label: Link, name: link, widget: string }
